### ISSUE TITLE
Issues with dependency

### ISSUE THREAD

**Issue by KillerSnackers** [esx-framework/esx_datastore#2]
My log says:
 Render/ Could not find dependency esx_datastore for resource esx_accessories.
[     54922] [    GTAProcess]               Render/ Error: Couldn't start resource esx_accessories.
[     54922] [    GTAProcess]               Render/ OnConnectionError: Couldn't start resource esx_accessories.
[     54985] [    GTAProcess]               Render/ Could not find dependency esx_addonaccount for resource esx_society.
[     54985] [    GTAProcess]               Render/ Error: Couldn't start resource esx_society.
[     54985] [    GTAProcess]               Render/ OnConnectionError: Couldn't start resource esx_society.
[     54985] [    GTAProcess]               Render/ Could not find dependency esx_addonaccount for resource esx_society.
[     54985] [    GTAProcess]               Render/ Could not start dependency esx_society for resource esx_mechanicjob.
[     54985] [    GTAProcess]               Render/ Error: Couldn't start resource esx_mechanicjob.
[     54985] [    GTAProcess]               Render/ OnConnectionError: Couldn't start resource esx_mechanicjob.

i cant join the server 
on The server mechanicjob, accessories and society starting without problems

**Comment by TheFantomas** [comment]
Problem with this commit: https://github.com/esx-framework/esx_datastore/commit/df1f7535524c0d8c3437a81812c49a7ea9105682.
