### ISSUE TITLE
spamming in console

### ISSUE THREAD

**Issue by Harry755** [esx-framework/esx_datastore#4]
[      script:oxmysql] Error: esx_datastore was unable to execute a query!
[      script:oxmysql] Query: INSERT INTO datastore_data (name, owner, data) VALUES (?, ?, ?)
[      script:oxmysql] ["user_glasses","char2:1ed75f95099195769a52edf08d05cb2a36047a12","{}"]
[      script:oxmysql] Duplicate entry 'user_glasses-char2:1ed75f95099195769a52edf08d05cb2a36047a12' for key 'index_datastore_data_name_owner'
[      script:oxmysql] Error: esx_datastore was unable to execute a query!
[      script:oxmysql] Query: INSERT INTO datastore_data (name, owner, data) VALUES (?, ?, ?)
[      script:oxmysql] ["user_helmet","char2:1ed75f95099195769a52edf08d05cb2a36047a12","{}"]
[      script:oxmysql] Duplicate entry 'user_helmet-char2:1ed75f95099195769a52edf08d05cb2a36047a12' for key 'index_datastore_data_name_owner'
[      script:oxmysql] Error: esx_datastore was unable to execute a query!
[      script:oxmysql] Query: INSERT INTO datastore_data (name, owner, data) VALUES (?, ?, ?)
[      script:oxmysql] ["user_ears","char2:1ed75f95099195769a52edf08d05cb2a36047a12","{}"]
[      script:oxmysql] Duplicate entry 'user_ears-char2:1ed75f95099195769a52edf08d05cb2a36047a12' for key 'index_datastore_data_name_owner'
[      script:oxmysql] Error: esx_datastore was unable to execute a query!
[      script:oxmysql] Query: INSERT INTO datastore_data (name, owner, data) VALUES (?, ?, ?)
[      script:oxmysql] ["user_mask","char2:1ed75f95099195769a52edf08d05cb2a36047a12","{}"]
[      script:oxmysql] Duplicate entry 'user_mask-char2:1ed75f95099195769a52edf08d05cb2a36047a12' for key 'index_datastore_data_name_owner'

**Comment by Gellipapa** [comment]
@Harry755 Hi! This can't happen by default it's likely that you are trying to use an older database. delete the contents of the datastore_data table and it should work fine.

**Comment by Harry755** [comment]
> @Harry755 Hi! This can't happen by default it's likely that you are trying to use an older database. delete the contents of the datastore_data table and it should work fine.

ok cleared that 
but 

[script:esx_datastore] SCRIPT ERROR: @esx_datastore/server/main.lua:5: esx_datastore was unable to execute a query!
[script:esx_datastore] Query: SELECT * FROM datastore_data LEFT JOIN datastore ON datastore_data.name = datastore.name UNION SELECT * FROM datastore_data RIGHT JOIN datastore ON datastore_data.name = datastore.name
[script:esx_datastore] []
[script:esx_datastore] Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
[script:esx_datastore] > handler (@esx_datastore/server/main.lua:5)
[script:esx_datastore] > logError (@oxmysql/dist/build.js:24882)
[script:esx_datastore] > rawQuery (@oxmysql/dist/build.js:25056)
[script:esx_datastore] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:esx_addonacco] SCRIPT ERROR: @esx_addonaccount/server/main.lua:18: table index is nil
[script:esx_addonacco] > handler (@esx_addonaccount/server/main.lua:18)
[script:esx_addonacco] > rawQuery (@oxmysql/dist/build.js:25047)
[script:esx_addonacco] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by Gellipapa** [comment]
@Harry755 Hi! It's okey, you should change main database and tables, correct collections. Your collections mixed and don't working sql database. This is not esx problem this is fivem server setup problem. You can find a solution in google.
